clear

echo "                                                                         "
echo "                                                                         "
echo "                                                                         "
echo "                                     ▄▄▄      ▓█████▄  ███▄ ▄███▓ ▄▄▄     ▄▄▄█████▓"
echo "                                    ▒████▄    ▒██▀ ██▌▓██▒▀█▀ ██▒▒████▄   ▓  ██▒ ▓▒"
echo "                                    ▒██  ▀█▄  ░██   █▌▓██    ▓██░▒██  ▀█▄ ▒ ▓██░ ▒░"
echo "                                    ░██▄▄▄▄██ ░▓█▄   ▌▒██    ▒██ ░██▄▄▄▄██░ ▓██▓ ░ "
echo "                                     ▓█   ▓██▒░▒████▓ ▒██▒   ░██▒ ▓█   ▓██▒ ▒██▒ ░ "
echo "                                     ▒▒   ▓▒█░ ▒▒▓  ▒ ░ ▒░   ░  ░ ▒▒   ▓▒█░ ▒ ░░ "
echo "                                     ▒   ▒▒ ░ ░ ▒  ▒ ░  ░      ░  ▒   ▒▒ ░   ░  "
echo "                                    ░   ▒    ░ ░  ░ ░      ░     ░   ▒    ░   "
echo "                                        ░  ░   ░           ░         ░  ░   "
echo "                                             ░     "





python3 /home/ubuntu/Desktop/cric2/A.py &
python3 /home/ubuntu/Desktop/cric2/AA.py &
python3 /home/ubuntu/Desktop/cric2/AAC.py &
python3 /home/ubuntu/Desktop/cric2/AACG.py &
python3 /home/ubuntu/Desktop/cric2/AACI.py &
python3 /home/ubuntu/Desktop/cric2/AACIU.py &
python3 /home/ubuntu/Desktop/cric2/AACIW.py &
python3 /home/ubuntu/Desktop/cric2/AADI.py &
python3 /home/ubuntu/Desktop/cric2/AAIC.py &
python3 /home/ubuntu/Desktop/cric2/AAL.py &
python3 /home/ubuntu/Desktop/cric2/AAMC.py &
python3 /home/ubuntu/Desktop/cric2/AAME.py &
python3 /home/ubuntu/Desktop/cric2/AAN.py &
python3 /home/ubuntu/Desktop/cric2/AAOI.py &
python3 /home/ubuntu/Desktop/cric2/AAON.py &
python3 /home/ubuntu/Desktop/cric2/AAP.py &
python3 /home/ubuntu/Desktop/cric2/AAPL.py &
python3 /home/ubuntu/Desktop/cric2/AAQC.py &
python3 /home/ubuntu/Desktop/cric2/AAT.py &
python3 /home/ubuntu/Desktop/cric2/AATC.py &
python3 /home/ubuntu/Desktop/cric2/AAU.py &
python3 /home/ubuntu/Desktop/cric2/AAWW.py &
python3 /home/ubuntu/Desktop/cric2/AB.py &
python3 /home/ubuntu/Desktop/cric2/ABB.py &
python3 /home/ubuntu/Desktop/cric2/ABBV.py &
python3 /home/ubuntu/Desktop/cric2/ABC.py &
python3 /home/ubuntu/Desktop/cric2/ABCB.py &
python3 /home/ubuntu/Desktop/cric2/ABCL.py &
python3 /home/ubuntu/Desktop/cric2/ABCM.py &
python3 /home/ubuntu/Desktop/cric2/ABEO.py &
python3 /home/ubuntu/Desktop/cric2/ABEV.py &
python3 /home/ubuntu/Desktop/cric2/ABG.py &
python3 /home/ubuntu/Desktop/cric2/ABGI.py &
python3 /home/ubuntu/Desktop/cric2/ABIO.py &
python3 /home/ubuntu/Desktop/cric2/ABM.py &
python3 /home/ubuntu/Desktop/cric2/ABMD.py &
python3 /home/ubuntu/Desktop/cric2/ABNB.py &
python3 /home/ubuntu/Desktop/cric2/ABOS.py &
python3 /home/ubuntu/Desktop/cric2/ABR.py &
python3 /home/ubuntu/Desktop/cric2/ABSI.py &
python3 /home/ubuntu/Desktop/cric2/ABST.py &
python3 /home/ubuntu/Desktop/cric2/ABT.py &
python3 /home/ubuntu/Desktop/cric2/ABTX.py &
python3 /home/ubuntu/Desktop/cric2/ABUS.py &
python3 /home/ubuntu/Desktop/cric2/ABVC.py &
python3 /home/ubuntu/Desktop/cric2/AC.py &
python3 /home/ubuntu/Desktop/cric2/ACA.py &
python3 /home/ubuntu/Desktop/cric2/ACAB.py &
python3 /home/ubuntu/Desktop/cric2/ACABU.py &
python3 /home/ubuntu/Desktop/cric2/ACAD.py &
python3 /home/ubuntu/Desktop/cric2/ACAH.py &
python3 /home/ubuntu/Desktop/cric2/ACAHU.py &
python3 /home/ubuntu/Desktop/cric2/ACAHW.py &
python3 /home/ubuntu/Desktop/cric2/ACAQ.py &
python3 /home/ubuntu/Desktop/cric2/ACAXR.py &
python3 /home/ubuntu/Desktop/cric2/ACAXU.py &
python3 /home/ubuntu/Desktop/cric2/ACAXW.py &
python3 /home/ubuntu/Desktop/cric2/ACEL.py &
python3 /home/ubuntu/Desktop/cric2/ACER.py &
python3 /home/ubuntu/Desktop/cric2/ACET.py &
python3 /home/ubuntu/Desktop/cric2/ACEV.py &
python3 /home/ubuntu/Desktop/cric2/ACEVU.py &
python3 /home/ubuntu/Desktop/cric2/ACGL.py &
python3 /home/ubuntu/Desktop/cric2/ACGLN.py &
python3 /home/ubuntu/Desktop/cric2/ACGLO.py &
python3 /home/ubuntu/Desktop/cric2/ACH.py &
python3 /home/ubuntu/Desktop/cric2/ACHC.py &
python3 /home/ubuntu/Desktop/cric2/ACHL.py &
python3 /home/ubuntu/Desktop/cric2/ACHR.py &
python3 /home/ubuntu/Desktop/cric2/ACHV.py &
python3 /home/ubuntu/Desktop/cric2/ACI.py &
python3 /home/ubuntu/Desktop/cric2/ACII.py &
python3 /home/ubuntu/Desktop/cric2/ACIU.py &
python3 /home/ubuntu/Desktop/cric2/ACIW.py &
python3 /home/ubuntu/Desktop/cric2/ACM.py &
python3 /home/ubuntu/Desktop/cric2/ACMR.py &
python3 /home/ubuntu/Desktop/cric2/ACN.py &
python3 /home/ubuntu/Desktop/cric2/ACNB.py &
python3 /home/ubuntu/Desktop/cric2/ACON.py &
python3 /home/ubuntu/Desktop/cric2/ACONW.py &
python3 /home/ubuntu/Desktop/cric2/ACOR.py &
python3 /home/ubuntu/Desktop/cric2/ACP.py &
python3 /home/ubuntu/Desktop/cric2/ACQR.py &
python3 /home/ubuntu/Desktop/cric2/ACQRU.py &
python3 /home/ubuntu/Desktop/cric2/ACR.py &
python3 /home/ubuntu/Desktop/cric2/ACRO.py &
python3 /home/ubuntu/Desktop/cric2/ACRS.py &
python3 /home/ubuntu/Desktop/cric2/ACRX.py &
python3 /home/ubuntu/Desktop/cric2/ACST.py &
python3 /home/ubuntu/Desktop/cric2/ACT.py &
python3 /home/ubuntu/Desktop/cric2/ACTD.py &
python3 /home/ubuntu/Desktop/cric2/ACU.py &
python3 /home/ubuntu/Desktop/cric2/ACV.py &
python3 /home/ubuntu/Desktop/cric2/ACVA.py &
python3 /home/ubuntu/Desktop/cric2/ACXP.py &
python3 /home/ubuntu/Desktop/cric2/ADAG.py &
python3 /home/ubuntu/Desktop/cric2/ADAL.py &
python3 /home/ubuntu/Desktop/cric2/ADAP.py &
python3 /home/ubuntu/Desktop/cric2/ADBE.py &
python3 /home/ubuntu/Desktop/cric2/ADC.py &
python3 /home/ubuntu/Desktop/cric2/ADCT.py &
python3 /home/ubuntu/Desktop/cric2/ADER.py &
python3 /home/ubuntu/Desktop/cric2/ADERW.py &
python3 /home/ubuntu/Desktop/cric2/ADES.py &
python3 /home/ubuntu/Desktop/cric2/ADEX.py &
python3 /home/ubuntu/Desktop/cric2/ADGI.py &
python3 /home/ubuntu/Desktop/cric2/ADI.py &
python3 /home/ubuntu/Desktop/cric2/ADIL.py &
python3 /home/ubuntu/Desktop/cric2/ADM.py &
python3 /home/ubuntu/Desktop/cric2/ADMA.py &
python3 /home/ubuntu/Desktop/cric2/ADMP.py &
python3 /home/ubuntu/Desktop/cric2/ADN.py &
python3 /home/ubuntu/Desktop/cric2/ADNT.py &
python3 /home/ubuntu/Desktop/cric2/ADOC.py &
python3 /home/ubuntu/Desktop/cric2/ADOCR.py &
python3 /home/ubuntu/Desktop/cric2/ADOCW.py &
python3 /home/ubuntu/Desktop/cric2/ADP.py &
python3 /home/ubuntu/Desktop/cric2/ADPT.py &
python3 /home/ubuntu/Desktop/cric2/ADRA.py &
python3 /home/ubuntu/Desktop/cric2/ADRT.py &
python3 /home/ubuntu/Desktop/cric2/ADSE.py &
python3 /home/ubuntu/Desktop/cric2/ADSEW.py &
python3 /home/ubuntu/Desktop/cric2/ADSK.py &
python3 /home/ubuntu/Desktop/cric2/ADT.py &
python3 /home/ubuntu/Desktop/cric2/ADTH.py &
python3 /home/ubuntu/Desktop/cric2/ADTHW.py &
python3 /home/ubuntu/Desktop/cric2/ADTN.py &
python3 /home/ubuntu/Desktop/cric2/ADTX.py &
python3 /home/ubuntu/Desktop/cric2/ADUS.py &
python3 /home/ubuntu/Desktop/cric2/ADV.py &
python3 /home/ubuntu/Desktop/cric2/ADVM.py &
python3 /home/ubuntu/Desktop/cric2/ADX.py &
python3 /home/ubuntu/Desktop/cric2/ADXN.py &
python3 /home/ubuntu/Desktop/cric2/AE.py &
python3 /home/ubuntu/Desktop/cric2/AEAC.py &
python3 /home/ubuntu/Desktop/cric2/AEE.py &
python3 /home/ubuntu/Desktop/cric2/AEF.py &
python3 /home/ubuntu/Desktop/cric2/AEFC.py &
python3 /home/ubuntu/Desktop/cric2/AEG.py &
python3 /home/ubuntu/Desktop/cric2/AEI.py &
python3 /home/ubuntu/Desktop/cric2/AEIS.py &
python3 /home/ubuntu/Desktop/cric2/AEL.py &
python3 /home/ubuntu/Desktop/cric2/AEM.py &
python3 /home/ubuntu/Desktop/cric2/AEMD.py &
python3 /home/ubuntu/Desktop/cric2/AENZ.py &
python3 /home/ubuntu/Desktop/cric2/AEO.py &
python3 /home/ubuntu/Desktop/cric2/AEP.py &
python3 /home/ubuntu/Desktop/cric2/AEPPZ.py &
python3 /home/ubuntu/Desktop/cric2/AER.py &
python3 /home/ubuntu/Desktop/cric2/AERC.py &
python3 /home/ubuntu/Desktop/cric2/AERI.py &
python3 /home/ubuntu/Desktop/cric2/AES.py &
python3 /home/ubuntu/Desktop/cric2/AESC.py &
python3 /home/ubuntu/Desktop/cric2/AESC.py &
python3 /home/ubuntu/Desktop/cric2/AEVA.py &
python3 /home/ubuntu/Desktop/cric2/AESE.py &
python3 /home/ubuntu/Desktop/cric2/AEY.py &
python3 /home/ubuntu/Desktop/cric2/AEYE.py &
python3 /home/ubuntu/Desktop/cric2/AEZS.py &
python3 /home/ubuntu/Desktop/cric2/AFAC.py &
python3 /home/ubuntu/Desktop/cric2/AFACW.py &
python3 /home/ubuntu/Desktop/cric2/AFAQ.py &
python3 /home/ubuntu/Desktop/cric2/AFAQU.py &
python3 /home/ubuntu/Desktop/cric2/AFAQW.py &
python3 /home/ubuntu/Desktop/cric2/AFB.py &
python3 /home/ubuntu/Desktop/cric2/AFBI.py &
python3 /home/ubuntu/Desktop/cric2/AFCG.py &
python3 /home/ubuntu/Desktop/cric2/AFG.py &
python3 /home/ubuntu/Desktop/cric2/AFGB.py &
python3 /home/ubuntu/Desktop/cric2/AFGC.py &
python3 /home/ubuntu/Desktop/cric2/AFGD.py &
python3 /home/ubuntu/Desktop/cric2/AFGE.py &
python3 /home/ubuntu/Desktop/cric2/AFI.py &
python3 /home/ubuntu/Desktop/cric2/AFIB.py &
python3 /home/ubuntu/Desktop/cric2/AFL.py &
python3 /home/ubuntu/Desktop/cric2/AFMD.py &
python3 /home/ubuntu/Desktop/cric2/AFRM.py &
python3 /home/ubuntu/Desktop/cric2/AFT.py &
python3 /home/ubuntu/Desktop/cric2/AFTR.py &
python3 /home/ubuntu/Desktop/cric2/AFYA.py &
python3 /home/ubuntu/Desktop/cric2/AG.py &
python3 /home/ubuntu/Desktop/cric2/AGAC.py &
python3 /home/ubuntu/Desktop/cric2/AGBA.py &
python3 /home/ubuntu/Desktop/cric2/AGBAR.py &
python3 /home/ubuntu/Desktop/cric2/AGBAW.py &
python3 /home/ubuntu/Desktop/cric2/AGCB.py &
python3 /home/ubuntu/Desktop/cric2/AGCO.py &
python3 /home/ubuntu/Desktop/cric2/AGD.py &
python3 /home/ubuntu/Desktop/cric2/AGE.py &
python3 /home/ubuntu/Desktop/cric2/AGEN.py &
python3 /home/ubuntu/Desktop/cric2/AGFS.py &
python3 /home/ubuntu/Desktop/cric2/AGFY.py &
python3 /home/ubuntu/Desktop/cric2/AGGR.py &
python3 /home/ubuntu/Desktop/cric2/AGGRU.py &
python3 /home/ubuntu/Desktop/cric2/AGI.py &
python3 /home/ubuntu/Desktop/cric2/AGIL.py &
python3 /home/ubuntu/Desktop/cric2/AGILW.py &
python3 /home/ubuntu/Desktop/cric2/AGIO.py &
python3 /home/ubuntu/Desktop/cric2/AGL.py &
python3 /home/ubuntu/Desktop/cric2/AGLE.py &
python3 /home/ubuntu/Desktop/cric2/AGM.py &
python3 /home/ubuntu/Desktop/cric2/AGMH.py &
python3 /home/ubuntu/Desktop/cric2/AGNC.py &
python3 /home/ubuntu/Desktop/cric2/AGNCM.py &
python3 /home/ubuntu/Desktop/cric2/AGNCN.py &
python3 /home/ubuntu/Desktop/cric2/AGNCO.py &
python3 /home/ubuntu/Desktop/cric2/AGNCP.py &
python3 /home/ubuntu/Desktop/cric2/AGO.py &
python3 /home/ubuntu/Desktop/cric2/AGR.py &
python3 /home/ubuntu/Desktop/cric2/AGRI.py &
python3 /home/ubuntu/Desktop/cric2/AGRIW.py &
python3 /home/ubuntu/Desktop/cric2/AGRO.py &
python3 /home/ubuntu/Desktop/cric2/AGRX.py &
python3 /home/ubuntu/Desktop/cric2/AGS.py &
python3 /home/ubuntu/Desktop/cric2/AGTC.py &
python3 /home/ubuntu/Desktop/cric2/AGTI.py &
python3 /home/ubuntu/Desktop/cric2/AGX.py &
python3 /home/ubuntu/Desktop/cric2/AGYS.py &
python3 /home/ubuntu/Desktop/cric2/AHCO.py &
python3 /home/ubuntu/Desktop/cric2/AHG.py &
python3 /home/ubuntu/Desktop/cric2/AHH.py &
python3 /home/ubuntu/Desktop/cric2/AHI.py &
python3 /home/ubuntu/Desktop/cric2/AHPA.py &
python3 /home/ubuntu/Desktop/cric2/AHPAU.py &
python3 /home/ubuntu/Desktop/cric2/AHPAW.py &
python3 /home/ubuntu/Desktop/cric2/AHPI.py &
python3 /home/ubuntu/Desktop/cric2/AHRN.py &
python3 /home/ubuntu/Desktop/cric2/AHRNU.py &
python3 /home/ubuntu/Desktop/cric2/AHT.py &
python3 /home/ubuntu/Desktop/cric2/AI.py &
python3 /home/ubuntu/Desktop/cric2/AIB.py &
python3 /home/ubuntu/Desktop/cric2/AIC.py &
python3 /home/ubuntu/Desktop/cric2/AIF.py &
python3 /home/ubuntu/Desktop/cric2/AIG.py &
python3 /home/ubuntu/Desktop/cric2/AIH.py &
python3 /home/ubuntu/Desktop/cric2/AIHS.py &
python3 /home/ubuntu/Desktop/cric2/AIKI.py &
python3 /home/ubuntu/Desktop/cric2/AIM.py &
python3 /home/ubuntu/Desktop/cric2/AIMAU.py &
python3 /home/ubuntu/Desktop/cric2/AIMC.py &
python3 /home/ubuntu/Desktop/cric2/AIN.py &
python3 /home/ubuntu/Desktop/cric2/AINC.py &
python3 /home/ubuntu/Desktop/cric2/AINV.py &
python3 /home/ubuntu/Desktop/cric2/AIO.py &
python3 /home/ubuntu/Desktop/cric2/AIO.py &
python3 /home/ubuntu/Desktop/cric2/AIP.py &
python3 /home/ubuntu/Desktop/cric2/AIR.py &
python3 /home/ubuntu/Desktop/cric2/AIRC.py &
python3 /home/ubuntu/Desktop/cric2/AIRG.py &
python3 /home/ubuntu/Desktop/cric2/AIRI.py &
python3 /home/ubuntu/Desktop/cric2/AIRS.py &
python3 /home/ubuntu/Desktop/cric2/AIRT.py &
python3 /home/ubuntu/Desktop/cric2/AIRTP.py &
python3 /home/ubuntu/Desktop/cric2/AIT.py &
python3 /home/ubuntu/Desktop/cric2/AIU.py &
python3 /home/ubuntu/Desktop/cric2/AIV.py &
python3 /home/ubuntu/Desktop/cric2/AIZ.py &
python3 /home/ubuntu/Desktop/cric2/AIZN.py &
python3 /home/ubuntu/Desktop/cric2/AJG.py &
python3 /home/ubuntu/Desktop/cric2/AJRD.py &
python3 /home/ubuntu/Desktop/cric2/AJX.py &
python3 /home/ubuntu/Desktop/cric2/AJXA.py &
python3 /home/ubuntu/Desktop/cric2/AKA.py &
python3 /home/ubuntu/Desktop/cric2/AKAM.py &
python3 /home/ubuntu/Desktop/cric2/AKAN.py &
python3 /home/ubuntu/Desktop/cric2/AKBA.py &
python3 /home/ubuntu/Desktop/cric2/AKIC.py &
python3 /home/ubuntu/Desktop/cric2/AKR.py &
python3 /home/ubuntu/Desktop/cric2/AKRO.py &
python3 /home/ubuntu/Desktop/cric2/AKTS.py &
python3 /home/ubuntu/Desktop/cric2/AKTX.py &
python3 /home/ubuntu/Desktop/cric2/AKU.py &
python3 /home/ubuntu/Desktop/cric2/AKUS.py &
python3 /home/ubuntu/Desktop/cric2/AKYA.py &
python3 /home/ubuntu/Desktop/cric2/ALB.py &
python3 /home/ubuntu/Desktop/cric2/ALBO.py &
python3 /home/ubuntu/Desktop/cric2/ALC.py &
python3 /home/ubuntu/Desktop/cric2/ALCC.py &
python3 /home/ubuntu/Desktop/cric2/ALCO.py &
python3 /home/ubuntu/Desktop/cric2/ALDX.py &
python3 /home/ubuntu/Desktop/cric2/ALE.py &
python3 /home/ubuntu/Desktop/cric2/ALEC.py &
python3 /home/ubuntu/Desktop/cric2/ALEX.py &
python3 /home/ubuntu/Desktop/cric2/ALF.py &
python3 /home/ubuntu/Desktop/cric2/ALFIW.py &
python3 /home/ubuntu/Desktop/cric2/ALG.py &
python3 /home/ubuntu/Desktop/cric2/ALGM.py &
python3 /home/ubuntu/Desktop/cric2/ALGN.py &
python3 /home/ubuntu/Desktop/cric2/ALGS.py &
python3 /home/ubuntu/Desktop/cric2/ALGT.py &
python3 /home/ubuntu/Desktop/cric2/ALHC.py &
python3 /home/ubuntu/Desktop/cric2/ALIT.py &
python3 /home/ubuntu/Desktop/cric2/ALJJ.py &
python3 /home/ubuntu/Desktop/cric2/ALK.py &
python3 /home/ubuntu/Desktop/cric2/ALKS.py &
python3 /home/ubuntu/Desktop/cric2/ALLE.py &
python3 /home/ubuntu/Desktop/cric2/ALLG.py &
python3 /home/ubuntu/Desktop/cric2/ALLK.py &
python3 /home/ubuntu/Desktop/cric2/ALLO.py &
python3 /home/ubuntu/Desktop/cric2/ALLR.py &
python3 /home/ubuntu/Desktop/cric2/ALLT.py &
python3 /home/ubuntu/Desktop/cric2/ALLY.py &
python3 /home/ubuntu/Desktop/cric2/ALNA.py &
python3 /home/ubuntu/Desktop/cric2/ALNY.py &
python3 /home/ubuntu/Desktop/cric2/ALOR.py &
python3 /home/ubuntu/Desktop/cric2/ALORU.py &
python3 /home/ubuntu/Desktop/cric2/ALORW.py &
python3 /home/ubuntu/Desktop/cric2/ALOT.py &
python3 /home/ubuntu/Desktop/cric2/ALPA.py &
python3 /home/ubuntu/Desktop/cric2/ALPAW.py &
python3 /home/ubuntu/Desktop/cric2/ALPN.py &
python3 /home/ubuntu/Desktop/cric2/ALPP.py &
python3 /home/ubuntu/Desktop/cric2/ALR.py &
python3 /home/ubuntu/Desktop/cric2/ALRM.py &
python3 /home/ubuntu/Desktop/cric2/ALRN.py &
python3 /home/ubuntu/Desktop/cric2/ALRS.py &
python3 /home/ubuntu/Desktop/cric2/ALSA.py &
python3 /home/ubuntu/Desktop/cric2/ALSAR.py &
python3 /home/ubuntu/Desktop/cric2/ALSAW.py &
python3 /home/ubuntu/Desktop/cric2/ALSN.py &
python3 /home/ubuntu/Desktop/cric2/ALT.py &
python3 /home/ubuntu/Desktop/cric2/ALTG.py &
python3 /home/ubuntu/Desktop/cric2/ALTO.py &
python3 /home/ubuntu/Desktop/cric2/ALTR.py &
python3 /home/ubuntu/Desktop/cric2/ALTU.py &
python3 /home/ubuntu/Desktop/cric2/ALTUU.py &
python3 /home/ubuntu/Desktop/cric2/ALTUW.py &
python3 /home/ubuntu/Desktop/cric2/ALV.py &
python3 /home/ubuntu/Desktop/cric2/ALVR.py &
python3 /home/ubuntu/Desktop/cric2/ALX.py &
python3 /home/ubuntu/Desktop/cric2/ALXO.py &
python3 /home/ubuntu/Desktop/cric2/ALYA.py &
python3 /home/ubuntu/Desktop/cric2/ALZN.py &
python3 /home/ubuntu/Desktop/cric2/AM.py &
python3 /home/ubuntu/Desktop/cric2/AMAL.py &
python3 /home/ubuntu/Desktop/cric2/AMAM.py &
python3 /home/ubuntu/Desktop/cric2/AMAO.py &
python3 /home/ubuntu/Desktop/cric2/AMAOW.py &
python3 /home/ubuntu/Desktop/cric2/AMAT.py &
python3 /home/ubuntu/Desktop/cric2/AMBA.py &
python3 /home/ubuntu/Desktop/cric2/AMBC.py &
python3 /home/ubuntu/Desktop/cric2/AMBO.py &
python3 /home/ubuntu/Desktop/cric2/AMBP.py &
python3 /home/ubuntu/Desktop/cric2/AMC.py &
python3 /home/ubuntu/Desktop/cric2/AMCI.py &
python3 /home/ubuntu/Desktop/cric2/AMCIW.py &
python3 /home/ubuntu/Desktop/cric2/AMCR.py &
python3 /home/ubuntu/Desktop/cric2/AMCX.py &
python3 /home/ubuntu/Desktop/cric2/AMD.py &
python3 /home/ubuntu/Desktop/cric2/AME.py &
python3 /home/ubuntu/Desktop/cric2/AMED.py &
python3 /home/ubuntu/Desktop/cric2/AMEH.py &
python3 /home/ubuntu/Desktop/cric2/AMG.py &
python3 /home/ubuntu/Desktop/cric2/AMGN.py &
python3 /home/ubuntu/Desktop/cric2/AMH.py &
python3 /home/ubuntu/Desktop/cric2/AMK.py &
python3 /home/ubuntu/Desktop/cric2/AMKR.py &
python3 /home/ubuntu/Desktop/cric2/AMLX.py &
python3 /home/ubuntu/Desktop/cric2/AMN.py &
python3 /home/ubuntu/Desktop/cric2/AMNB.py &
python3 /home/ubuntu/Desktop/cric2/AMOT.py &
python3 /home/ubuntu/Desktop/cric2/AMOV.py &
python3 /home/ubuntu/Desktop/cric2/AMP.py &
python3 /home/ubuntu/Desktop/cric2/AMPE.py &
python3 /home/ubuntu/Desktop/cric2/AMPG.py &
python3 /home/ubuntu/Desktop/cric2/AMPGW.py &
python3 /home/ubuntu/Desktop/cric2/AMPH.py &
python3 /home/ubuntu/Desktop/cric2/AMPI.py &
python3 /home/ubuntu/Desktop/cric2/AMPL.py &
python3 /home/ubuntu/Desktop/cric2/AMPS.py &
python3 /home/ubuntu/Desktop/cric2/AMPY.py &
python3 /home/ubuntu/Desktop/cric2/AMR.py &
python3 /home/ubuntu/Desktop/cric2/AMRC.py &
python3 /home/ubuntu/Desktop/cric2/AMRK.py &
python3 /home/ubuntu/Desktop/cric2/AMRN.py &
python3 /home/ubuntu/Desktop/cric2/AMRS.py &
python3 /home/ubuntu/Desktop/cric2/AMRX.py &
python3 /home/ubuntu/Desktop/cric2/AMS.py &
python3 /home/ubuntu/Desktop/cric2/AMSC.py &
python3 /home/ubuntu/Desktop/cric2/AMSF.py &
python3 /home/ubuntu/Desktop/cric2/AMST.py &
python3 /home/ubuntu/Desktop/cric2/AMSWA.py &
python3 /home/ubuntu/Desktop/cric2/AMT.py &
python3 /home/ubuntu/Desktop/cric2/AMTB.py &
python3 /home/ubuntu/Desktop/cric2/AMTD.py &
python3 /home/ubuntu/Desktop/cric2/AMTI.py &
python3 /home/ubuntu/Desktop/cric2/AMTX.py &
python3 /home/ubuntu/Desktop/cric2/AMWD.py &
python3 /home/ubuntu/Desktop/cric2/AMWL.py &
python3 /home/ubuntu/Desktop/cric2/AMX.py &
python3 /home/ubuntu/Desktop/cric2/AMYT.py &
python3 /home/ubuntu/Desktop/cric2/AMZN.py &
python3 /home/ubuntu/Desktop/cric2/AN.py &
python3 /home/ubuntu/Desktop/cric2/ANAB.py &
python3 /home/ubuntu/Desktop/cric2/ANAC.py &
python3 /home/ubuntu/Desktop/cric2/ANAT.py &
python3 /home/ubuntu/Desktop/cric2/ANDE.py &
python3 /home/ubuntu/Desktop/cric2/ANEB.py &
python3 /home/ubuntu/Desktop/cric2/ANET.py &
python3 /home/ubuntu/Desktop/cric2/ANF.py &
python3 /home/ubuntu/Desktop/cric2/ANGH.py &
python3 /home/ubuntu/Desktop/cric2/ANDE.py &
python3 /home/ubuntu/Desktop/cric2/ANEB.py &
python3 /home/ubuntu/Desktop/cric2/ANET.py &
python3 /home/ubuntu/Desktop/cric2/ANF.py &
python3 /home/ubuntu/Desktop/cric2/ANGH.py &
python3 /home/ubuntu/Desktop/cric2/ANGHW.py &
python3 /home/ubuntu/Desktop/cric2/ANGI.py &
python3 /home/ubuntu/Desktop/cric2/ANGN.py &
python3 /home/ubuntu/Desktop/cric2/ANGO.py &
python3 /home/ubuntu/Desktop/cric2/ANIK.py &
python3 /home/ubuntu/Desktop/cric2/ANIP.py &
python3 /home/ubuntu/Desktop/cric2/ANIX.py &
python3 /home/ubuntu/Desktop/cric2/ANPC.py &
python3 /home/ubuntu/Desktop/cric2/ANSS.py &
python3 /home/ubuntu/Desktop/cric2/ANTE.py &
python3 /home/ubuntu/Desktop/cric2/ANTM.py &
python3 /home/ubuntu/Desktop/cric2/ANTX.py &
python3 /home/ubuntu/Desktop/cric2/ANVS.py &
python3 /home/ubuntu/Desktop/cric2/ANY.py &
python3 /home/ubuntu/Desktop/cric2/ANZU.py &
python3 /home/ubuntu/Desktop/cric2/ANZUU.py &
python3 /home/ubuntu/Desktop/cric2/ANZUW.py &
python3 /home/ubuntu/Desktop/cric2/AOD.py &
python3 /home/ubuntu/Desktop/cric2/AOGO.py &
python3 /home/ubuntu/Desktop/cric2/AOGOW.py &
python3 /home/ubuntu/Desktop/cric2/AOMR.py &
python3 /home/ubuntu/Desktop/cric2/AON.py &
python3 /home/ubuntu/Desktop/cric2/AORT.py &
python3 /home/ubuntu/Desktop/cric2/AOS.py &
python3 /home/ubuntu/Desktop/cric2/AOSL.py &
python3 /home/ubuntu/Desktop/cric2/AOUT.py &
python3 /home/ubuntu/Desktop/cric2/AP.py &
python3 /home/ubuntu/Desktop/cric2/APA.py &
python3 /home/ubuntu/Desktop/cric2/APAC.py &
python3 /home/ubuntu/Desktop/cric2/APACW.py &
python3 /home/ubuntu/Desktop/cric2/APAM.py &
python3 /home/ubuntu/Desktop/cric2/APCA.py &
python3 /home/ubuntu/Desktop/cric2/APCX.py &
python3 /home/ubuntu/Desktop/cric2/APCXW.py &
python3 /home/ubuntu/Desktop/cric2/APD.py &
python3 /home/ubuntu/Desktop/cric2/APDN.py &
python3 /home/ubuntu/Desktop/cric2/APEI.py &
python3 /home/ubuntu/Desktop/cric2/APEN.py &
python3 /home/ubuntu/Desktop/cric2/APG.py &
python3 /home/ubuntu/Desktop/cric2/APGB.py &
python3 /home/ubuntu/Desktop/cric2/APH.py &
python3 /home/ubuntu/Desktop/cric2/API.py &
python3 /home/ubuntu/Desktop/cric2/APLD.py &
python3 /home/ubuntu/Desktop/cric2/APLE.py &
python3 /home/ubuntu/Desktop/cric2/APLS.py &
python3 /home/ubuntu/Desktop/cric2/APLT.py &
python3 /home/ubuntu/Desktop/cric2/APM.py &
python3 /home/ubuntu/Desktop/cric2/APMI.py &
python3 /home/ubuntu/Desktop/cric2/APMIU.py &
python3 /home/ubuntu/Desktop/cric2/APMIW.py &
python3 /home/ubuntu/Desktop/cric2/APN.py &
python3 /home/ubuntu/Desktop/cric2/APO.py &
python3 /home/ubuntu/Desktop/cric2/APOG.py &
python3 /home/ubuntu/Desktop/cric2/APP.py &
python3 /home/ubuntu/Desktop/cric2/APPF.py &
python3 /home/ubuntu/Desktop/cric2/APPH.py &
python3 /home/ubuntu/Desktop/cric2/APPHW.py &
python3 /home/ubuntu/Desktop/cric2/APPN.py &
python3 /home/ubuntu/Desktop/cric2/APPS.py &
python3 /home/ubuntu/Desktop/cric2/APRE.py &
python3 /home/ubuntu/Desktop/cric2/APRN.py &
python3 /home/ubuntu/Desktop/cric2/APSG.py &
python3 /home/ubuntu/Desktop/cric2/APT.py &
python3 /home/ubuntu/Desktop/cric2/APTMU.py &
python3 /home/ubuntu/Desktop/cric2/APTMW.py &
python3 /home/ubuntu/Desktop/cric2/APTO.py &
python3 /home/ubuntu/Desktop/cric2/APTS.py &
python3 /home/ubuntu/Desktop/cric2/APTV.py &
python3 /home/ubuntu/Desktop/cric2/APTX.py &
python3 /home/ubuntu/Desktop/cric2/APVO.py &
python3 /home/ubuntu/Desktop/cric2/APWC.py &
python3 /home/ubuntu/Desktop/cric2/APXI.py &
python3 /home/ubuntu/Desktop/cric2/APXIU.py &
python3 /home/ubuntu/Desktop/cric2/APXIW.py &
python3 /home/ubuntu/Desktop/cric2/APYX.py &
python3 /home/ubuntu/Desktop/cric2/AQB.py &
python3 /home/ubuntu/Desktop/cric2/AQMS.py &
python3 /home/ubuntu/Desktop/cric2/AQN.py &
python3 /home/ubuntu/Desktop/cric2/AQNA.py &
python3 /home/ubuntu/Desktop/cric2/AQNB.py &
python3 /home/ubuntu/Desktop/cric2/AQNU.py &
python3 /home/ubuntu/Desktop/cric2/AQST.py &
python3 /home/ubuntu/Desktop/cric2/AQUA.py &
python3 /home/ubuntu/Desktop/cric2/AR.py &
python3 /home/ubuntu/Desktop/cric2/ARAV.py &
python3 /home/ubuntu/Desktop/cric2/ARAY.py &
python3 /home/ubuntu/Desktop/cric2/ARBE.py &
python3 /home/ubuntu/Desktop/cric2/ARBEW.py &
python3 /home/ubuntu/Desktop/cric2/ARBG.py &
python3 /home/ubuntu/Desktop/cric2/ARBGU.py &
python3 /home/ubuntu/Desktop/cric2/ARBGW.py &
python3 /home/ubuntu/Desktop/cric2/ARBK.py &
python3 /home/ubuntu/Desktop/cric2/ARC.py &
python3 /home/ubuntu/Desktop/cric2/%launcher%


